apiVersion: v1
kind: Template
metadata:
  name: vertx-health-check-booster
  annotations:
    description: This template creates a Vert.x application providing health check endpoint to be consumed by Kubernetes.
    tags: instant-app
parameters:
- name: SOURCE_REPOSITORY_URL
  description: The source URL for the application
  displayName: Source URL
  required: true
- name: SOURCE_REPOSITORY_REF
  description: The branch name for the application
  displayName: Source Branch
  value: master
  required: true
- name: SOURCE_REPOSITORY_DIR
  description: The location within the source repo of the application
  displayName: Source Directory
  value: .
  required: true
- name: GITHUB_WEBHOOK_SECRET
  description: A secret string used to configure the GitHub webhook.
  displayName: GitHub Webhook Secret
  required: true
  from: '[a-zA-Z0-9]{40}'
  generate: expression

objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: health-check-vertx
    labels:
      booster: health-check-vertx
  spec: {}

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: runtime-health-check-vertx
    labels:
      booster: health-check-vertx
  spec:
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: health-check-vertx
    labels:
      booster: health-check-vertx
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: health-check-vertx:latest
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      #contextDir: ${SOURCE_REPOSITORY_DIR}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: runtime-health-check-vertx:latest
        incremental: true
        env:
        - name: MAVEN_ARGS_APPEND
          value: "-pl ${SOURCE_REPOSITORY_DIR}"
        - name: ARTIFACT_DIR
          value: "${SOURCE_REPOSITORY_DIR}/target"
      type: Source
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/port: "9779"
      prometheus.io/scrape: "true"
    labels:
      app: health-check-vertx
      group: io.openshift.booster
    name: health-check-vertx
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: health-check-vertx
      group: io.openshift.booster

- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: health-check-vertx
      group: io.openshift.booster
    name: health-check-vertx
  spec:
    replicas: 1
    selector:
      app: health-check-vertx
      group: io.openshift.booster
    template:
      metadata:
        labels:
          app: health-check-vertx
          group: io.openshift.booster
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: health-check-vertx:master
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /api/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
          name: vertx
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 3
            timeoutSeconds: 1
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - vertx
        from:
          kind: ImageStreamTag
          name: health-check-vertx:latest

- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: health-check-vertx
      group: io.openshift.booster
    name: health-check-vertx
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: health-check-vertx
